### ISSUE TITLE
App Authetification

### ISSUE THREAD

**Issue by sub2sub2** [sub2sub2/AI-LINUX-RUST#25]

**Comment by sub2sub2** [comment]
As-Is: gRPC metadata (pre-defined)
To-be:
- (?) --> App Register --> give token to App.
- Searching (회사 케이스 찾아보기)
1) App이 신뢰할 수 있는 건지 어떻게 확인(?).
2) 그 이후 인증 정책 --> 서로 public 키 교환 후 각자의 private key랑 뭐를 하면 같은 값이 나온다. (?)

**Comment by sseoreo** [comment]
전제: 서버 운영자가 어떤 앱이 접근할지 이미 알고 합의가 된 상황
서버 실행할 때, 미리 App정보가 저장된 DB를 읽어들여 접근 권한 부여.
DB 구현 방식은 DB파일(e.g., JSON파일) 또는 API로 등록.

Q. DB에 App의 어떤 정보를 저장해야 하는가?
N:1, N:N 비교는 서버 운영자가 정의

Q. 서버에 언제 인증을 해야하는지?
최초 연결? 매 요청 시? 현재 매요청시 인증하는 방식으로 (오버헤드 우려)

**Comment by hyunsube** [comment]
우선 매 요청시 인증하는 방식으로 구현하기
