### ISSUE TITLE
Make structure for AI model

### ISSUE THREAD

**Issue by sub2sub2** [sub2sub2/AI-LINUX-RUST#26]
모델 개발자 입장에서 모델을 어떻게 agent에 등록(?) 을 할 것인지?
- 우리의 서버가 있을 때, 함부로 개발자가 등록하면 위험하다.
- 개인의 서버여도 위험하다.
--> 안정성 어떻게 확보를 하나? 절차?

unit test?

**Comment by hyunsube** [comment]
모델을 추가 / 등록하고자 할 때 필요한
- cpp 기반의 모델 실행 파일 (메시지 핸들하는 부분 / 모델 로드하는 부분을 구현해야함)
- d-bus 통신을 위한 이름 정의
- 무슨 데이터를 받는지? (agent) --> 모델은 데이터를 어떻게 agent에게 받는지? (우선 파일 경로로 생각 / agent는 파일로 저장.)
- 아웃풋도 파일?
--> 추후 최적화 필요.

**Comment by hyunsube** [comment]
우선 파일 경로를 주고 받는 형태로 구현
